name = "baseline"
path = 'data/101/val' 
test_label_path = "data/101/val_no_label.csv"
test_path = "" #checkpoint path
test = True
batch_size = 16
gpus = 4
lr = 3e-4
num_workers = 2
max_epoch = 100
version = 0